package dao;

import entity.Privance;
import java.util.List;

public interface PrivanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int insert(Privance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    Privance selectByPrimaryKey(String provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    List<Privance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Privance record);
}